# Correlations for stocks I am interested in

* Time Frame: 5Y

In [1]:
import yfinance as yf
import numpy as np
import pandas as pd

univ = ['RR','CRML','OPEN','DVLT','BBAI', 'BITF', 'IXHL', 'ONDS', 'RGTI', 'ASTS', 'LPTH', 'BURU', 'PATH', 'DNUT', 'GLD', 'DEFT']
px = yf.download(univ, start="2020-01-01", auto_adjust=False)['Adj Close']
ret = px / px.shift() - 1

[*********************100%***********************]  16 of 16 completed

In [2]:
ret.corr()

Ticker,ASTS,BBAI,BITF,BURU,CRML,DEFT,DNUT,DVLT,GLD,IXHL,LPTH,ONDS,OPEN,PATH,RGTI,RR
Ticker,,,,,,,,,,,,,,,,
ASTS,1.000000,0.118971,0.202365,0.063139,0.118022,0.292696,0.105154,0.048850,-0.002907,0.004909,0.123354,0.211773,0.197227,0.268075,0.199991,0.144036
BBAI,0.118971,1.000000,0.263031,-0.016122,0.118488,0.358468,0.031941,0.054842,0.027586,0.028774,0.079155,0.142313,0.152788,0.122296,0.215898,0.248773
BITF,0.202365,0.263031,1.000000,-0.017400,0.103344,0.471553,0.186231,0.043324,0.096490,-0.029673,0.149343,0.240723,0.280923,0.388747,0.240378,0.126479
BURU,0.063139,-0.016122,-0.017400,1.000000,0.004264,-0.011492,0.001046,0.047133,-0.032530,0.002042,0.012772,0.035572,-0.000163,-0.016324,-0.043473,-0.014906
CRML,0.118022,0.118488,0.103344,0.004264,1.000000,0.091994,0.050879,-0.014446,0.070566,-0.034932,0.089702,0.061018,0.064151,0.049265,0.039563,0.085147
DEFT,0.292696,0.358468,0.471553,-0.011492,0.091994,1.000000,0.137936,0.049323,0.063784,-0.095509,0.187018,0.241810,0.181620,0.410801,0.246172,0.251985
DNUT,0.105154,0.031941,0.186231,0.001046,0.050879,0.137936,1.000000,-0.041123,0.050249,-0.032209,0.099460,0.122904,0.200406,0.201336,0.074904,0.029930
DVLT,0.048850,0.054842,0.043324,0.047133,-0.014446,0.049323,-0.041123,1.000000,-0.003233,0.040862,0.038530,0.030231,0.060438,0.027044,0.076393,0.002485
GLD,-0.002907,0.027586,0.096490,-0.032530,0.070566,0.063784,0.050249,-0.003233,1.000000,-0.096108,0.046317,-0.002474,0.056652,0.073106,0.030360,0.016385
IXHL,0.004909,0.028774,-0.029673,0.002042,-0.034932,-0.095509,-0.032209,0.040862,-0.096108,1.000000,-0.008175,0.006428,0.065520,-0.011949,0.071749,0.034061
LPTH,0.123354,0.079155,0.149343,0.012772,0.089702,0.187018,0.099460,0.038530,0.046317,-0.008175,1.000000,0.210876,0.150716,0.186788,0.226635,0.138561
ONDS,0.211773,0.142313,0.240723,0.035572,0.061018,0.241810,0.122904,0.030231,-0.002474,0.006428,0.210876,1.000000,0.272664,0.240505,0.210139,0.243825
OPEN,0.197227,0.152788,0.280923,-0.000163,0.064151,0.181620,0.200406,0.060438,0.056652,0.065520,0.150716,0.272664,1.000000,0.399406,0.251475,0.109527
PATH,0.268075,0.122296,0.388747,-0.016324,0.049265,0.410801,0.201336,0.027044,0.073106,-0.011949,0.186788,0.240505,0.399406,1.000000,0.261105,0.138352
RGTI,0.199991,0.215898,0.240378,-0.043473,0.039563,0.246172,0.074904,0.076393,0.030360,0.071749,0.226635,0.210139,0.251475,0.261105,1.000000,0.212305
RR,0.144036,0.248773,0.126479,-0.014906,0.085147,0.251985,0.029930,0.002485,0.016385,0.034061,0.138561,0.243825,0.109527,0.138352,0.212305,1.000000

In [4]:
import yfinance as yf
univ = ['RR','CRML','OPEN','ONDS', 'RGTI', 'ASTS', 'LPTH','PATH', 'USAR', 'UPS', 'OBDC', 'SRFM']
px = yf.download(univ, start="2020-01-01", auto_adjust=False)['Adj Close']
ret = px / px.shift() - 1

[*********************100%***********************]  12 of 12 completed

In [5]:
ret.corr()

Ticker,ASTS,CRML,LPTH,OBDC,ONDS,OPEN,PATH,RGTI,RR,SRFM,UPS,USAR
Ticker,,,,,,,,,,,,
ASTS,1.000000,0.102482,0.117175,0.129287,0.209394,0.198071,0.263951,0.195813,0.141930,0.117355,0.129367,0.086353
CRML,0.102482,1.000000,0.048722,0.015881,0.043924,0.062111,0.020070,0.016660,0.078019,0.029861,0.059599,0.127285
LPTH,0.117175,0.048722,1.000000,0.174984,0.205797,0.147706,0.176724,0.218725,0.127773,0.093825,0.082899,0.083526
OBDC,0.129287,0.015881,0.174984,1.000000,0.196752,0.266548,0.333065,0.191920,0.036962,0.140062,0.299496,0.000200
ONDS,0.209394,0.043924,0.205797,0.196752,1.000000,0.272526,0.243529,0.204962,0.237148,0.105334,0.169109,0.122166
OPEN,0.198071,0.062111,0.147706,0.266548,0.272526,1.000000,0.405239,0.253744,0.105295,0.114686,0.224274,0.007935
PATH,0.263951,0.020070,0.176724,0.333065,0.243529,0.405239,1.000000,0.259589,0.144740,0.167377,0.263362,0.011489
RGTI,0.195813,0.016660,0.218725,0.191920,0.204962,0.253744,0.259589,1.000000,0.208698,0.183310,0.124512,0.100573
RR,0.141930,0.078019,0.127773,0.036962,0.237148,0.105295,0.144740,0.208698,1.000000,0.120985,0.170858,-0.024714
SRFM,0.117355,0.029861,0.093825,0.140062,0.105334,0.114686,0.167377,0.183310,0.120985,1.000000,0.123061,0.003301
UPS,0.129367,0.059599,0.082899,0.299496,0.169109,0.224274,0.263362,0.124512,0.170858,0.123061,1.000000,0.057771
USAR,0.086353,0.127285,0.083526,0.000200,0.122166,0.007935,0.011489,0.100573,-0.024714,0.003301,0.057771,1.000000